# Generated by Django 6.1.1 on 2026-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('banco', models.CharField(blank=True, max_length=50, verbose_name='Banco')),
                ('telefono_pago', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Pago Móvil')),
                ('cedula_pago', models.CharField(blank=True, max_length=20, verbose_name='Cédula Pago Móvil')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['nombre'],
            },
        ),
    ]
