# Generated by Django 6.1.1 on 2026-09-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('numero', 'Numérico'), ('texto', 'Texto'), ('booleano', 'Sí/No')], default='numero', max_length=10, verbose_name='Tipo')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor numérico')),
                ('valor_texto', models.CharField(blank=True, max_length=200, verbose_name='Valor texto')),
                ('valor_booleano', models.BooleanField(blank=True, null=True, verbose_name='Valor Sí/No')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['codigo'],
            },
        ),
    ]
