# Generated by Django 6.1.1 on 2026-09-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('doble_piso', 'Doble Piso'), ('yutong', 'Yutong'), ('poltrona', 'Poltrona'), ('ejecutivo', 'Ejecutivo'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad total')),
                ('configuracion_asientos', models.JSONField(default=dict, help_text='Ej: {"pisos": 1, "filas": 15, "columnas": 4, "pasillo": 2}', verbose_name='Configuración de asientos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('destinos', models.ManyToManyField(related_name='rutas_destino', to='core.oficina', verbose_name='Oficinas destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='core.oficina', verbose_name='Oficina origen')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto USD')),
                ('seguro_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Seguro USD')),
                ('seguro_opcional', models.BooleanField(default=True, verbose_name='¿Seguro opcional?')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_destino', to='core.oficina', verbose_name='Oficina destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_origen', to='core.oficina', verbose_name='Oficina origen')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['origen', 'destino'],
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
