# Generated by Django 6.1.1 on 2026-09-21 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bus_ruta_tarifa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('es_discapacitado', models.BooleanField(default=False, verbose_name='¿Discapacitado?')),
                ('es_tercera_edad', models.BooleanField(default=False, verbose_name='¿Tercera edad?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['cedula'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio USD')),
                ('seguro_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Seguro USD')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('cerrado_venta', models.BooleanField(default=False, verbose_name='Venta cerrada')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bus', verbose_name='Bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, verbose_name='Número')),
                ('fila', models.PositiveIntegerField(verbose_name='Fila')),
                ('columna', models.PositiveIntegerField(verbose_name='Columna')),
                ('piso', models.PositiveIntegerField(default=1, verbose_name='Piso')),
                ('lado', models.CharField(blank=True, choices=[('ventana', 'Ventana'), ('pasillo', 'Pasillo')], max_length=10, verbose_name='Lado')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('reservado_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Reservado hasta')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='core.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['viaje', 'piso', 'fila', 'columna'],
            },
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['fecha', 'estado'], name='core_viaje_fecha_fa912c_idx'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['viaje', 'estado'], name='core_asient_viaje_i_6272a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('viaje', 'numero')},
        ),
    ]
