# Generated by Django 6.1.1 on 2026-09-21 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_viaje_asiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajero_cedula', models.CharField(db_index=True, max_length=20, verbose_name='Cédula del pasajero')),
                ('pasajero_nombre', models.CharField(max_length=100, verbose_name='Nombre del pasajero')),
                ('pasajero_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del pasajero')),
                ('pasajero_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp del pasajero')),
                ('tipo_pasajero', models.CharField(choices=[('normal', 'Normal'), ('discapacitado', 'Discapacitado'), ('tercera_edad', 'Tercera edad'), ('cortesia', 'Cortesía')], default='normal', max_length=20, verbose_name='Tipo de pasajero')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Descuento')),
                ('monto_tarifa_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto tarifa USD')),
                ('monto_seguro_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto seguro USD')),
                ('monto_descuento_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto descuento USD')),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total USD')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Tasa BCV')),
                ('monto_total_bs', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto total Bs.')),
                ('codigo_qr', models.CharField(max_length=50, unique=True, verbose_name='Código QR')),
                ('estado', models.CharField(choices=[('vendido', 'Vendido'), ('usado', 'Usado'), ('cancelado', 'Cancelado con crédito'), ('no_show', 'No se presentó'), ('reprogramado', 'Reprogramado')], default='vendido', max_length=20, verbose_name='Estado')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('fecha_chequeo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de chequeo')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asiento', verbose_name='Asiento')),
                ('chequeado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos_chequeados', to=settings.AUTH_USER_MODEL, verbose_name='Chequeado por')),
                ('liberado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos_liberados', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('vendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendido por')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='core.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=20, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('monto_tarifa_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa original USD')),
                ('monto_seguro_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Seguro original USD')),
                ('saldo_tarifa_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo tarifa USD')),
                ('saldo_seguro_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo seguro USD')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('parcial', 'Usado parcialmente'), ('usado', 'Usado totalmente'), ('vencido', 'Vencido')], default='vigente', max_length=20, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('boleto_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_generados', to='core.boleto', verbose_name='Boleto que originó el crédito')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('reserva', 'Reserva temporal'), ('liberacion_reserva', 'Liberación por vencimiento'), ('cancelacion', 'Cancelación por el pasajero'), ('no_show', 'No se presentó'), ('reprogramacion', 'Reprogramación'), ('bloqueo', 'Bloqueado por admin'), ('desbloqueo', 'Desbloqueado por admin'), ('liberacion_manual', 'Liberación manual')], max_length=30, verbose_name='Tipo de movimiento')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.asiento', verbose_name='Asiento')),
                ('boleto_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boleto', verbose_name='Boleto relacionado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Asiento',
                'verbose_name_plural': 'Movimientos de Asientos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['codigo_qr'], name='core_boleto_codigo__2667b5_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['pasajero_cedula'], name='core_boleto_pasajer_2b85da_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['viaje', 'estado'], name='core_boleto_viaje_i_fa38ec_idx'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['cedula', 'estado'], name='core_credit_cedula_dbb39b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoasiento',
            index=models.Index(fields=['asiento', '-fecha_hora'], name='core_movimi_asiento_f0c66b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoasiento',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='core_movimi_usuario_c87986_idx'),
        ),
    ]
