# Generated by Django 6.1.1 on 2026-09-21 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boleto_credito_movimientoasiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha_suspension',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de suspensión'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='motivo_suspension',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo de suspensión'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='suspendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_suspendidos', to=settings.AUTH_USER_MODEL, verbose_name='Suspendido por'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('suspendido', 'Suspendido'), ('reprogramado', 'Reprogramado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='hora',
            field=models.TimeField(verbose_name='Hora de salida'),
        ),
    ]
