# Generated by Django 6.1.1 on 2026-09-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_viaje_fecha_suspension_viaje_motivo_suspension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('doble_piso', 'Doble Piso'), ('yutong', 'Yutong'), ('poltrona', 'Poltrona'), ('ejecutivo', 'Ejecutivo'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de bus')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad total')),
                ('pisos', models.PositiveIntegerField(default=1, verbose_name='Cantidad de pisos')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Plantilla de Bus',
                'verbose_name_plural': 'Plantillas de Buses',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='core.plantillabus', verbose_name='Plantilla de asientos'),
        ),
        migrations.CreateModel(
            name='PlantillaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=5, verbose_name='Número de asiento')),
                ('fila', models.PositiveIntegerField(verbose_name='Fila')),
                ('columna', models.PositiveIntegerField(verbose_name='Columna')),
                ('piso', models.PositiveIntegerField(default=1, verbose_name='Piso')),
                ('lado', models.CharField(blank=True, choices=[('ventana', 'Ventana'), ('pasillo', 'Pasillo'), ('', 'No aplica')], max_length=10, verbose_name='Lado')),
                ('tipo', models.CharField(choices=[('asiento', 'Asiento'), ('escalera', 'Escalera'), ('baño', 'Baño'), ('conductor', 'Conductor'), ('vacio', 'Vacío')], default='asiento', max_length=20, verbose_name='Tipo')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='core.plantillabus', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Posición de Plantilla',
                'verbose_name_plural': 'Posiciones de Plantilla',
                'ordering': ['plantilla', 'piso', 'fila', 'columna'],
                'unique_together': {('plantilla', 'piso', 'fila', 'columna')},
            },
        ),
    ]
