# Generated by Django 6.1.1 on 2026-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plantillabus_bus_plantilla_plantillaasiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('asiento', 'Asiento'), ('escalera', 'Escalera'), ('baño', 'Baño'), ('vacio', 'Vacío')], default='asiento', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.CharField(blank=True, max_length=5, verbose_name='Número'),
        ),
    ]
