# Generated by Django 6.1.1 on 2026-09-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_asiento_unique_together_asiento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_reservados', to='core.cliente', verbose_name='Reservado por'),
        ),
    ]
