# Generated by Django 6.1.1 on 2026-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asiento_reservado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='puestos_descuento_max',
            field=models.PositiveIntegerField(blank=True, help_text='Si se deja vacío, se usa el valor del parámetro 110', null=True, verbose_name='Máximo de puestos con descuento'),
        ),
    ]
