# Generated by Django 6.1.1 on 2026-09-22 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bus_puestos_descuento_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('cantidad_boletos', models.PositiveIntegerField(verbose_name='Cantidad de boletos')),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total USD')),
                ('monto_total_bs', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto total Bs.')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Tasa BCV')),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pendiente_verificacion', 'Pago cargado, pendiente de verificación'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente_pago', max_length=30, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='core.cliente', verbose_name='Cliente')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada por')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='core.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pago_movil', 'Pago Móvil'), ('transferencia', 'Transferencia bancaria'), ('efectivo_usd', 'Efectivo USD'), ('efectivo_bs', 'Efectivo Bs.'), ('punto_venta', 'Punto de venta')], max_length=20, verbose_name='Método de pago')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto USD')),
                ('monto_bs', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Bs.')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Tasa BCV')),
                ('banco_origen', models.CharField(blank=True, max_length=50, verbose_name='Banco de origen')),
                ('telefono_origen', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de origen')),
                ('cedula_origen', models.CharField(blank=True, max_length=20, verbose_name='Cédula de origen')),
                ('referencia', models.CharField(blank=True, max_length=30, verbose_name='Número de referencia')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/', verbose_name='Imagen del comprobante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddField(
            model_name='boleto',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='core.transaccion', verbose_name='Transacción'),
        ),
    ]
