# Generated by Django 6.1.1 on 2026-09-25 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaccion_pago_boleto_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(blank=True, help_text='Destino específico al que va este viaje (debe estar entre los destinos de la ruta)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='core.oficina', verbose_name='Destino del viaje'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='configuracion_asientos',
            field=models.JSONField(blank=True, default=dict, help_text="Campo obsoleto. Se mantiene por compatibilidad. Usar 'plantilla'.", verbose_name='Configuración de asientos (obsoleto)'),
        ),
    ]
