# Generated by Django 6.1.1 on 2026-09-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_viaje_destino_alter_bus_configuracion_asientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
    ]
