# Generated by Django 6.1.1 on 2026-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_viaje_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio USD'),
        ),
    ]
