# Generated by Django 6.1.1 on 2026-10-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_viaje_precio_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
