# Generated by Django 6.1.1 on 2026-10-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ruta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('pago_movil', 'Pago Móvil'), ('transferencia', 'Transferencia bancaria'), ('efectivo_usd', 'Efectivo USD'), ('efectivo_bs', 'Efectivo Bs.'), ('punto_venta', 'Punto de venta')], max_length=50, verbose_name='Método de pago'),
        ),
    ]
