# Generated by Django 6.1.1 on 2026-10-01 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pago_metodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='dispositivo_venta',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dispositivo / User-Agent'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='numero_liquidacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de liquidación'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='oficina_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_destino', to='core.oficina', verbose_name='Oficina destino'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='oficina_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_oficina', to='core.oficina', verbose_name='Oficina que vendió'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='vendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_vendidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que vendió'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='estado',
            field=models.CharField(choices=[('vendido', 'Vendido'), ('usado', 'Usado'), ('cancelado', 'Cancelado con crédito'), ('no_show', 'No se presentó'), ('reprogramado', 'Reprogramado'), ('liquidado', 'Liquidado'), ('no_liquidado', 'No liquidado')], default='vendido', max_length=20, verbose_name='Estado'),
        ),
    ]
