# Generated by Django 6.1.1 on 2026-10-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_transaccion_dispositivo_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('pendiente_verificacion', 'Pendiente de verificación de pago'), ('vendido', 'Vendido'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='estado',
            field=models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificación'), ('vendido', 'Vendido'), ('usado', 'Usado'), ('cancelado', 'Cancelado con crédito'), ('no_show', 'No se presentó'), ('reprogramado', 'Reprogramado'), ('liquidado', 'Liquidado'), ('no_liquidado', 'No liquidado')], default='pendiente_verificacion', max_length=30, verbose_name='Estado'),
        ),
    ]
