# Generated by Django 6.1.1 on 2026-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_asiento_estado_alter_boleto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoasiento',
            name='estado_anterior',
            field=models.CharField(max_length=30, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='movimientoasiento',
            name='estado_nuevo',
            field=models.CharField(max_length=30, verbose_name='Estado nuevo'),
        ),
    ]
